version: 0.0
os: ubuntu
files:
 - source: .
   destination: /var/www/html/hospital
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root
