name: Push-to-EC2
run-name: ${{ github.actor }} is deploying to AWS EC2 server ${{ secrets.EC2_HOST }}

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

env:
  PHP_VERSION: '8.x'

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    environment: production
    # concurrency: production

    steps:
      - name: Checkout the files
        # uses: actions/checkout@v2
        uses: actions/checkout@v4
        with:
          path: main
      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Install Composer
        uses: "ramsey/composer-install@v2"
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
